<div class="CM-popupflyin-statistics-form">
    <label for="daily-date-from">Date from:</label>
    <input type="text" class="datepicker" readonly="true" name="daily-date-from" id="daily-date-from" value="<?php echo date("Y-m-01");?>">
    <label for="daily-date-to">Date to:</label>
    <input type="text" class="datepicker" readonly="true" name="daily-date-to" id="daily-date-to" value="<?php echo date("Y-m-d");?>">
    <button id="send-statistics-data-daily">Filter</button>
    <button id="clear-data-daily">Clear Dates</button>
</div>
<div id="CM-popupflyin-statistics-daily-result-container" class="result-container">
    
</div>