<div class="CM-popupflyin-statistics-form">
    <label for="period-date-from">Date from:</label>
    <input type="text" class="datepicker" readonly="true" name="period-date-from" id="period-date-from" value="<?php echo date("Y-m-01");?>">
    <label for="period-date-to">Date to:</label>
    <input type="text" class="datepicker" readonly="true" name="period-date-to" id="period-date-to" value="<?php echo date("Y-m-d");?>">
    <button id="send-statistics-data-period">Filter</button>
    <button id="clear-data-period">Clear Dates</button>
</div>
<div id="CM-popupflyin-statistics-period-result-container" class="result-container">
    
</div>